version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:19.04
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-12-jdk openjdk-12-jre
           git clone --depth=1 https://github.com/PradyX/android_kernel_xiaomi_sdm660 -b $CIRCLE_BRANCH wip2
           cd wip2
           git clone --depth=1 https://github.com/PradyX/ShellScripts -b master kscripts
           source ./kscripts/envsetup.sh
           ./kscripts/circle.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
